metrics:
  global:
    scrape_interval: 15s

  configs:
    - name: genstudio-app
      scrape_configs:
        - job_name: 'backend'
          static_configs:
            - targets: ['backend:8080']

      remote_write:
        - url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
          basic_auth:
            username: PROVIDED_PROM_USERNAME
            password: PROVIDED_PROM_PASSWORD
logs:
  configs:
    - name: genstudio-logs
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: https://logs-prod-021.grafana.net/loki/api/v1/push
          basic_auth:
            username: PROVIDED_LOKI_USERNAME
            password: PROVIDED_LOKI_PASSWORD
      scrape_configs:
        - job_name: backend-logs
          static_configs:
            - targets: [localhost]
              labels:
                job: backend
                __path__: /var/log/backend/*.log
traces:
  configs:
    - name: genstudio-traces
      receivers:
        otlp:
          protocols:
            http: {}
      remote_write:
        - endpoint: tempo-prod-15-prod-us-west-0.grafana.net:443
          basic_auth:
            username: PROVIDED_TEMPO_USERNAME
            password: PROVIDED_TEMPO_PASSWORD
