version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - backend-logs:/var/log/backend
    networks:
      observability: {}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      observability: {}

  grafana-agent:
    image: grafana/agent:latest
    container_name: grafana-agent
    volumes:
      - ./agent-config.yaml:/etc/agent-config.yaml
      - backend-logs:/var/log/backend
    command: ["--config.file=/etc/agent-config.yaml"]
    ports:
      - "4318:4318"
    networks:
      observability: {}

  backend-tests:
    build: ./backend
    command: ["npm", "run", "test:ci"]
    networks:
      observability: {}

  frontend-tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    command: ["npm", "run", "test:ci", "--", "--verbose"]
    networks:
      observability: {}

volumes:
  backend-logs:

networks:
  observability:
    driver: bridge
